package com.craws.mrx;

import org.junit.Test;

import static org.junit.Assert.*;

/**
 * Testing the GameState. Building a Demo-Map and Hunting the players across the board.
 * TODO: DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING
 *       DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING
 *       DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING
 *       DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING
 *       DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING
 *       DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING
 *       DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING
 *       DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING
 *       DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING
 *       DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING
 *       DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING
 *       DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING
 *       DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING
 *       DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING
 *       DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING
 *       DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING
 *       DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING
 *       DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING
 *       DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING
 *       DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING
 *       DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING
 *       DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING
 *       DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING
 *       DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING
 *       DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING
 *       DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING
 *       DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING
 *       DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING
 *       DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING *       DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING
 *       DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING
 *       DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING
 *       DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING
 *       DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING
 *       DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING
 *       DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING
 *       DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING
 *       DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING
 *       DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING
 *       DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING
 *       DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING
 *       DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING
 *       DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING
 *       DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING
 *       DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING
 *       DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING
 *       DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING
 *       DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING
 *       DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING
 *       DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING
 *       DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING
 *       DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING
 *       DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING
 *       DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING
 *       DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING
 *       DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING
 *       DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING *       DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING
 *       DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING
 *       DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING
 *       DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING
 *       DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING
 *       DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING
 *       DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING
 *       DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING
 *       DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING
 *       DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING
 *       DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING
 *       DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING
 *       DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING
 *       DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING
 *       DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVILOVING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING
 *       DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING
 *       DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING
 *       DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING
 *       DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING
 *       DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING
 *       DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING
 *       DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING
 *       DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING
 *       DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING
 *       DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING
 *       DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING
 *       DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING
 *       DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING DEVELOPING
 *

 */
public class GameStateUnitTest {
    @Test
    public void addition_isCorrect() {
        assertEquals(4, 2 + 2);
    }
}